Разметка внутренней страницы
htmlacademy-htmlcss/1723073-sedona-31 pull request #4
Opened 2021-05-24 19:25 UTC by DmitriyNechitaylov

И главной тоже

2021-05-25 16:46 UTC, Shramkoweb requested changes

2021-05-25 16:46 UTC, Shramkoweb commented on catalog.html
> +          <li><a>Гостиницы</a></li>
👍 круто)

2021-05-25 16:46 UTC, Shramkoweb commented on catalog.html
> +            <ul>
Можно без списка - зачем он тут? Или вам в лекции так показывали?

2021-05-25 16:46 UTC, Shramkoweb commented on catalog.html
> +                >
Отформатируй код пожалуйста - тут что то твориться страшное))

2021-05-25 16:46 UTC, Shramkoweb commented on catalog.html
> +                <input type="checkbox" name="pool" id="pool-id" checked /><label
id="pool-id" можно сократить просто до id="pool"

2021-05-25 16:46 UTC, Shramkoweb commented on catalog.html
> +                <input type="checkbox" name="parking" id="parking-id" /><label
```suggestion
                <input type="checkbox" name="parking" id="parking" /><label
```

2021-05-25 16:46 UTC, Shramkoweb commented on catalog.html
> +                <input type="checkbox" name="pool" id="pool-id" checked /><label
Ты забыл атрибут value у инпутов

2021-05-25 16:46 UTC, Shramkoweb commented on catalog.html
> +                <input type="checkbox" name="Wi-Fi" id="Wi-Fi-id" /><label
Почитай как делать множество чекбоксов или радио
https://up.htmlacademy.ru/htmlcss/31/module/2/item/6/14

По сути у тебя должен быть общий `name` у них всех, а разные `value`

2021-05-25 16:46 UTC, Shramkoweb commented on catalog.html
> +            <div class="position_1">
А что за классы?

2021-05-25 16:46 UTC, Shramkoweb commented on catalog.html
> +        >
форматирование

2021-05-25 16:46 UTC, Shramkoweb commented on catalog.html
> +            <div class="position_3"><p>Рейтинг: 9,2</p></div>
Плохое имя у классов, уже смотрел лекцию по CSS?

2021-05-26 04:46 UTC, DmitriyNechitaylov commented on catalog.html
> +            <ul>
Да, вроде в лекции был список

2021-05-26 04:51 UTC, DmitriyNechitaylov commented on catalog.html
> +            <div class="position_1">
Просто сам придумал

2021-05-26 04:53 UTC, DmitriyNechitaylov commented on catalog.html
> +        >
А как оно должно быть? Так pretier делает.

2021-05-26 04:54 UTC, DmitriyNechitaylov commented on catalog.html
> +            <div class="position_3"><p>Рейтинг: 9,2</p></div>
Ещё нет)

2021-05-26 16:38 UTC, DmitriyNechitaylov commented on catalog.html
> +                >
Это не я, это prettier)

2021-05-26 16:39 UTC, DmitriyNechitaylov commented on catalog.html
> +            <div class="position_3"><p>Рейтинг: 9,2</p></div>
Тогда классы пока уберем

2021-05-26 17:11 UTC, DmitriyNechitaylov commented on catalog.html
> +            <ul>
Вспомнил, я это взял из статьи "Методика семантической разметки - размечаем формы" А как по другому?

2021-05-26 17:11 UTC, DmitriyNechitaylov commented on catalog.html
> +                >
Я кое-что дописал, форматирование изменилось, сейчас все должно быть нормально

2021-05-26 17:14 UTC, DmitriyNechitaylov commented on catalog.html
> +            <ul>
Так, подожди, там нет списка, это я от себя уже добавил) Сейчас уберу

2021-05-26 19:58 UTC, Shramkoweb approved these changes
Ответь в телеге, что за мерж коммиты и почему я как автор в одном из коммитов?)) И вольем

2021-05-26 20:25 UTC, merged