Графика всех страниц
htmlacademy-htmlcss/1723073-sedona-31 pull request #5
Opened 2021-05-28 22:07 UTC by DmitriyNechitaylov

Добавил контентные изображения и фавиконки

2021-05-29 18:44 UTC, Shramkoweb requested changes

2021-05-29 18:44 UTC, Shramkoweb commented on catalog.html
> +                src="img/catalog/Amara Resort & Spa.jpg"
Пробелы нельзя в имени файлов.

2021-05-29 18:44 UTC, Shramkoweb commented on catalog.html
> +                src="img/catalog/Desert Quail Inn.jpg"
не используй верхний регистр букв и пробелы. Они не нужны в именах обычно. 

Используй разделитель тире `-`

2021-05-29 18:44 UTC, Shramkoweb commented on index.html
> +                alt="Дом"
Что за дом?https://weblind.ru/inner.html#image-content почитай как описывать alt

2021-05-30 07:57 UTC, DmitriyNechitaylov commented on catalog.html
> +                src="img/catalog/Amara Resort & Spa.jpg"
Я не ставил никаких пробелов

2021-05-30 07:59 UTC, DmitriyNechitaylov commented on catalog.html
> +                src="img/catalog/Amara Resort & Spa.jpg"
А, все, я понял, о чем ты.

2021-05-30 17:58 UTC, Shramkoweb approved these changes

2021-05-30 17:58 UTC, merged