Стилизация внутренней страницы
htmlacademy-htmlcss/1723073-sedona-31 pull request #7
Opened 2021-06-15 23:17 UTC by DmitriyNechitaylov

2021-06-16 19:25 UTC, Shramkoweb requested changes

2021-06-16 19:25 UTC, Shramkoweb commented on css/style.css
> +}
Я бы на `a` добавил класс и не использовал бы вложенность тут

2021-06-16 19:26 UTC, Shramkoweb commented on index.html
> +      <div class="bold-title">
`bold-title` - говорит мне что это жирный заголовок. Но я не вижу в разметке тут заголовка)) 

Обьясни плз)

2021-06-17 08:40 UTC, DmitriyNechitaylov commented on css/style.css
> +}
Не понимаю, что как

2021-06-17 08:48 UTC, DmitriyNechitaylov commented on index.html
> +      <div class="bold-title">
Многим блокам нужно добавить жирный шрифт и размер 21.
Часть из них заголовки, часть нет. Может быть, название неудачное. Bold-text?

2021-06-18 19:35 UTC, Shramkoweb commented on css/style.css
> +}
У тебя внутри .sort есть ссылки. На них добавить просто класс `<a class="sort-link"></a>`  и потм `.sort-link { color: var(--basic-black);}`

2021-06-18 19:36 UTC, Shramkoweb commented on index.html
> +      <div class="bold-title">
.bold-text  - 👍

2021-06-18 19:59 UTC, merged